name: Update Contributors README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  contrib-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README Contributors
        uses: akhilmhdvk/readme-contributors@v2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}