name: Update Contributors README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  contrib-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README Contributors
        uses: github-readme-contributors/github-readme-contributors@v1.3.0
        with:
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}